In [0]:
import numpy as np

In [0]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [0]:
N_input = 4
N_hidden = 3
N_output = 2

In [0]:
X = np.random.randn(4)
X

array([-0.35143057,  1.27013321,  0.38044872,  0.91947957])

In [0]:
weights_input_to_hidden = np.random.normal(0,scale=0.1, size = (N_input , N_hidden))
weights_hidden_to_output = np.random.normal(0,scale=0.1 , size = (N_hidden,N_output))

In [0]:
hidden_layer_in = np.dot(X,weights_input_to_hidden)

In [0]:
hidden_layer_in

array([-0.32084713, -0.05706925,  0.16985105])

In [0]:
hidden_layer_out = sigmoid(hidden_layer_in)
hidden_layer_out

array([0.42046931, 0.48573656, 0.54236097])

In [0]:
output_layer_in = np.dot(hidden_layer_in,weights_hidden_to_output)
output_layer_out = sigmoid(output_layer_in)

In [0]:
print('Hidden-layer Output:')
print(hidden_layer_out)
print('Output-layer Output:')
print(output_layer_out)

Hidden-layer Output:
[0.42046931 0.48573656 0.54236097]
Output-layer Output:
[0.51204649 0.49584701]
