<a href="https://colab.research.google.com/github/strange-hawk/ml_nn/blob/master/nn_backprop.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np

In [0]:
def sigmoid(x):
  return 1/(1+np.exp(-x))

In [0]:
x=np.array([0.5, 0.1, -0.2])
target = 0.6
learning_rate = 0.5

In [0]:
weights_input_hidden = np.array([[0.5,-0.6],
                                 [0.1,-0.2],
                                 [0.1,0.7]])
weights_hidden_output = np.array([0.1,-0.3])

forward pass

In [0]:
hidden_layer_input = np.dot(x,weights_input_hidden)
hidden_layer_output = sigmoid(hidden_layer_input)

In [0]:
output_layer_in = np.dot(hidden_layer_output,weights_hidden_output)
output = sigmoid(output_layer_in)

In [26]:
output

0.48497343084992534

bakpropagation

In [27]:
error = target-output
error

0.11502656915007464

In [30]:
output_error_term = error*output*(1-output)
delta_w_h_o = learning_rate*output_error_term*hidden_layer_output
delta_w_h_o
hidden_layer_output

array([0.55971365, 0.38698582])

In [0]:
hidden_error_term = np.dot(output_error_term,weights_hidden_output)*hidden_layer_output*(1-hidden_layer_output)

In [37]:
a = np.array([1,2])
b = np.array([3, 4])
a*b

array([3, 8])

In [0]:
delta_w_i_h = learning_rate*hidden_error_term*x[:,None]

In [41]:
print('Change in weights for hidden layer to output layer:')
print(delta_w_h_o)
print('Change in weights for input layer to hidden layer:')
print(delta_w_i_h)

Change in weights for hidden layer to output layer:
[0.00804047 0.00555918]
Change in weights for input layer to hidden layer:
[[ 1.77005547e-04 -5.11178506e-04]
 [ 3.54011093e-05 -1.02235701e-04]
 [-7.08022187e-05  2.04471402e-04]]
